### PR TITLE
Allow setting button visibility

### PR DESCRIPTION
**Pull request by gerriet**
For one or for all buttons via setButton()

### CODE REVIEW

**Comment by gerriet** [comment]
As the framework is providing the main view, it should be configurable to the users needs. For that purpose I have allowed setting the visibility of one or all buttons (making the SystemButtonType enum public).

**Comment by gerriet** [comment]
Hi David,

Thanks for the kind words and the acknowledgement in the README. Highly appreciated! And so are your thoughts about the pull requests.

I agree that the syntax you suggest is much _swiftier_. Originally I was just concerned about opening up the LuminaViewController to make the buttons visible. But ultimately, I have done just that with the last commits and think it is much better this way. So the resulting syntax would be:

```
let camera = LuminaViewController()
camera.switchButton.isHidden = true
```

Regarding the use of the framework: of course, forking it and changing it is always an option and the most probable one for __serious__ use. But even for light use, I imagine that adapting the UI is something that a number of people may want to use. For example, this is what I do: I use the UI as is when starting, combining two CoreML models to display the most probable environment (mostly indoor) as a text label. Tapping the image then gives you a table view of products that are relevant for the environment and this view is displayed transparently on top of the camera image (which is, when I need to hide the buttons). Tapping one product takes you to a detail view of the product. Tapping on the section header takes you back to the camera image (showing the buttons again). Other uses might be to disallow switching between cameras or to disallow the shutter (which I am considering).

**Comment by dokun1** [comment]
Sorry again for the delay - I have a lot going on with my full time job right now, so my time is not fully focused on this 😄 

After some thought, I'd like to make this a thing you can do, but I'd like for you to update the way the API is accessed.

For version 2 of this, I envision the ability to add UI elements that conform to some kind of protocol that allow access to some of the internal functions to be able to do what they should do. For example, a shutter button should be able to access default shutter behavior by virtue of the protocol it conforms to, but that button's function can be overridden if necessary. This means the entire camera will need re-architecture to a pattern where the UI and camera objects are entirely abstracted from one another, as the camera is currently "buried" underneath the UI.

For this right now, I'd like for you to make specific functions on the public API to show/hide each button. I'd rather keep `LuminaButton` internal for the time being, until we decide on the re-architecture decisions. Please re-do this with specific functions on the public API for each button. 

I apologize if it seems like it's taken a while to arrive here, and if this seems like a superfluous amount of change, but I think it's best to maintain v1 of this API for now.

**Comment by gerriet** [comment]
I have now implemented the change as requested (a separate method for each button, only one parameter) and reverted the earlier changes (public buttons). Took so long due to the flu :-(

I guess I have an idea what you are going for in version 2, but that will not be easy to get right (e.g. without making it too hard for the API user). But I think the separation of UI and functionality is worth striving for. Am looking forward to get back to my project using Lumina ...

**Comment by gerriet** [comment]
Accidentally closed

**Comment by dokun1** [comment]
@gerriet I promise to have resolution on this within the next 48 hours! I am working on a deadline to finish some video scripts for a tutorial I am writing right now 😄

**Comment by dokun1** [comment]
@gerriet this looks good and I am ok with the update. I need to add documentation to the main readme. I think this is a sign I need to add a documentation script with Jazzy to the travis-ci build.

Can you add documentation to the README for this? I can do it tonight my time if you don't have time to get to it. Will probably also cut a new release tomorrow.

**Comment by gerriet** [comment]
Added a paragraph to the README

**Comment by dokun1** [comment]
🎉 @gerriet

**Pull request merged**
