### PR TITLE
Upgraded to latest Swift syntax

### PR DESCRIPTION
**Pull request by SamuelMarks**
Nothing fancy, just fixing each compiler error and warning until it compiles without issue.

## Description
Started with the CocoaPods version. Wasn't getting the same errors opening up your workspace from your git repo.

## Motivation and Context
Can't compile on latest XCode without it. I'm running XCode 10.0 Beta 2 and targeting iOS 10.3+.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by dokun1** [comment]
Hi @SamuelMarks !!! Thank you so much for opening your first PR here 🎉 

However, it looks like the version you pulled from Cocoapods is a couple of versions old. This is confusing, because I've pushed v1.3.1 to the main trunk of Cocoapods, so you should have the latest. I can't merge this PR as is because it undoes a few changes from previous releases.

I have not yet installed the beta of Xcode 10 - can you try pulling the latest from `master` and building the `.xcworkspace` file again?

**Comment by SamuelMarks** [comment]
Hmm, that's weird, here are my relevant files:

**Podfile**
```
platform :ios, '10.3'

target 'debug-camera' do
  use_frameworks!
  pod 'Lumina'
end
```

**Podfile.lock**
```
PODS:
  - Lumina (1.2.1)

DEPENDENCIES:
  - Lumina

SPEC REPOS:
  https://github.com/cocoapods/specs.git:
    - Lumina

SPEC CHECKSUMS:
  Lumina: 8e27565633df88111745bbd25269d667a2fd69dc

PODFILE CHECKSUM: 164d1f9e9250c9ea3ee246ba46202b5360f7d499

COCOAPODS: 1.5.3
```

I'll try from master branch next.

**Comment by SamuelMarks** [comment]
Looks like that worked. New commit has updated this PR.

**Podfile**
```
platform :ios, '10.3'

target 'debug-camera' do
  use_frameworks!
  pod 'Lumina', :git => 'https://github.com/dokun1/Lumina.git', :branch => 'master'
end
```

**Podfile.lock**
```
platform :ios, '10.3'

target 'debug-camera' do
  use_frameworks!
  pod 'Lumina', :git => 'https://github.com/dokun1/Lumina.git', :branch => 'master'
end
Samuels-MacBook-Pro:debug-camera samuel$ cat Podfile.lock 
PODS:
  - Lumina (1.3.1)

DEPENDENCIES:
  - Lumina (from `https://github.com/dokun1/Lumina.git`, branch `master`)

EXTERNAL SOURCES:
  Lumina:
    :branch: master
    :git: https://github.com/dokun1/Lumina.git

CHECKOUT OPTIONS:
  Lumina:
    :commit: 5fca99f63899226e5383593d1b5402288b24323d
    :git: https://github.com/dokun1/Lumina.git

SPEC CHECKSUMS:
  Lumina: 32cb54017a0eed5539379cf1be77b16a13a8f681

PODFILE CHECKSUM: 0aadd2f6edba8244bb3bbdcb87a441fca22feddc

COCOAPODS: 1.5.3
```

**Comment by dokun1** [comment]
Thank you for this! I'm not yet ready to merge this, but I'll keep this up and merge it when iOS 12.0 drops out of beta. 🎉

**Comment by dokun1** [comment]
I'm sorry this got lost in the shuffle - thank you for your contribution nonetheless 🎉

**Pull request closed without merging**
